services:
  app:
    build: .
    container_name: manual-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
    environment:
      - NODE_ENV=development
      - PORT=3000
