services:
  app:
    build: .
    image: manual-app-image
    container_name: manual-app
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./src:/usr/src/app/src
    environment:
      - NODE_ENV=development
      - PORT=80
