name: Deploy All

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose development environment to deploy
        options:
          - dev
          - test
          - prod
        default: dev
      region:
        type: string
        description: Choose AWS region
        default: ap-southeast-2

jobs:
  deploy-ecr:
    uses: ./.github/workflows/ecr.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      region: ${{ github.event.inputs.region }}

  deploy-ecs:
    uses: ./.github/workflows/ecs.yml
    needs: deploy-ecr
    with:
      environment: ${{ github.event.inputs.environment }}
      region: ${{ github.event.inputs.region }}
